version: '3.8'

services:

  db_server:
    image: mariadb:10.5.8
    container_name: 'db_server'
    restart: always
    ports:
      - '33016:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'cv'
    volumes:
      - db_data:/var/lib/mysql
      - ./app:/app
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      interval: 5s
      retries: 5
    networks:
      - net-app

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: 'db-admin'
    ports:
      - '8101:80'
    environment:
      PMA_HOST: db_server
    depends_on:
      - db_server
    volumes:
      - db_admin_data:/var/www/html
      - ./app:/app
    networks:
      - net-app

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/app/
    depends_on:
      - db_server
    networks:
      - net-app

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db_server
    networks:
      - net-app

networks:
  net-app:
volumes:
  db_data:
  db_admin_data: